/**
 * @typedef {Object} CoreData
 * @prop {{}} tradeskill_mats Tradeskill material ID mapping
 * @prop {{}} gem_ids Gem ID mapping
 */
module.exports = {
    /** A mapping of tradeskill ingredient names to their IDs */
    tradeskill_mats: {
        "Aberration Mind Source": 0,
        "Animal Eye": 10,
        "Animal Tongue": 11,
        "Animal Tooth": 12,
        "Animal Wing": 13,
        "Beast Fur": 20,
        "Beast Limb": 21,
        "Beast Tooth": 22,
        "Beast Wing": 23,
        "Bird Nest": 122,
        "Chunk of Coal": 130,
        "Chunk of Graphite": 132,
        "Construct Power": 30,
        "Copper Ore": 133,
        "Dragon Eye": 40,
        "Dragon Scale": 41,
        "Dragon Tail": 42,
        "Elemental Energy": 50,
        "Fish Fin": 112,
        "Golden Apple": 121,
        Honeycomb: 123,
        "Humanoid Bone": 60,
        "Humanoid Flesh": 61,
        "Humanoid Limb": 62,
        "Lucky Coin": 141,
        "Magical Stone": 140,
        "Octopus Ink": 110,
        "Ooze Gel": 70,
        "Plant Branch": 80,
        "Plant Leaf": 81,
        "Plant Root": 82,
        "Plant Vine": 83,
        "Protection Stone": 142,
        "Rainbow Shard": 131,
        "Rune Stone": 143,
        "Serpent Eye": 90,
        "Serpent Tail": 91,
        "Serpent Tongue": 92,
        "Squid Tentacle": 113,
        "Turtle Shell": 111,
        "Vermin Eye": 100,
        "Vermin Tooth": 101,
        "Yellow Pollen": 120
    },

    /** Gem types vs their IDs */
    gem_ids: {
        Strength: 0,
        Health: 1,
        Coordination: 2,
        Agility: 3,
        Retaliation: 10,
        Restoration: 11,
        Dueling: 12,
        Sniping: 13,
        Sorcery: 14,
        Brawling: 15,
        Elusion: 16,
        Normalizing: 20,
        Hunting: 21,
        Taming: 22,
        Destruction: 23,
        Slaying: 24,
        Weathering: 25,
        Murdering: 26,
        Solidifying: 27,
        Weedwhacking: 28,
        Charming: 29,
        Exterminating: 30,
        Swiftness: 40,
        Potency: 41,
        Recklessness: 42,
        Resilience: 43,
        Retribution: 44,
        Recovery: 45,
        Harvesting: 46,
        Smithing: 47,
        Etching: 48,
        Wisdom: 50,
        Greed: 51,
        Luck: 52,
        Mastery: 53,
        Celerity: 60,
        Piercing: 61,
        Chronokinesis: 62,
        Endurance: 55
    }
};